- name: push to tomcat server
  
  hosts: ec2-jenkins
  become: true
  
  tasks:

    - name: Push War to Tomcat Server

      copy:

        src: "/var/lib/jenkins/workspace/DevOps WAR File Project/webapp/target/webapp.war"

        dest: "/var/lib/tomcat/webapps/webapp.war"

        force: yes
        
    - name: Restart Tomcat Service 
      ansible.builtin.service:
        name: tomcat
        state: restarted 










